### ISSUE TITLE
NaN em fator multiplicador, problema acusado pelos testes.

### ISSUE THREAD

**Issue by pablobion** [pedrosarkis/ahgorautilitarios#10]
![image](https://user-images.githubusercontent.com/50814036/120402371-7127d780-c318-11eb-879c-ad0cd55b94a3.png)

![image](https://user-images.githubusercontent.com/50814036/120402420-8c92e280-c318-11eb-816e-5b54647403a0.png)

**Comment by pedrosarkis** [comment]
Caraio Gildo. 
A sua versão do node é maior que 15?
